
##
# RLStevenson Theme Options
####

title:		RLStevenson
description:	'A Bootstrap based clone of the Hyde theme by mdo.'
freetext:	'Released under an MIT license - feel free to make pull requests.'
url:		/
baseurl:	/
paginate:	5
version:	0.1.0
colorscheme:	scheme-lightbrown

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

author:
 url:		https://www.exchangerate-api.com
 name:		'ExchangeRate-API'

github:
 repo:		https://github.com/ExchangeRate-API/rlstevenson

gems:		[jekyll-paginate]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'rlstevenson.gemspec']